//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halva.Package.Bootstrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Halva.Package.Bootstrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Developed by Studio ACE.
        /// </summary>
        internal static string AuthorSignature {
            get {
                return ResourceManager.GetString("AuthorSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing the game&apos;s assets. This will take a while..
        /// </summary>
        internal static string DecompressingDataText {
            get {
                return ResourceManager.GetString("DecompressingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Licesned under the MIT license..
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Halva Bootstrapper.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Version R1.01 ({0}).
        /// </summary>
        internal static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===========================================.
        /// </summary>
        internal static string SplitterText {
            get {
                return ResourceManager.GetString("SplitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating assets....
        /// </summary>
        internal static string UpdatingAssetsText {
            get {
                return ResourceManager.GetString("UpdatingAssetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database....
        /// </summary>
        internal static string UpdatingDatabaseText {
            get {
                return ResourceManager.GetString("UpdatingDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating engine....
        /// </summary>
        internal static string UpdatingEngineText {
            get {
                return ResourceManager.GetString("UpdatingEngineText", resourceCulture);
            }
        }
    }
}
