//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halva.Package.Packer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Halva.Package.Packer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed the assets..
        /// </summary>
        internal static string AssetsCompressedText {
            get {
                return ResourceManager.GetString("AssetsCompressedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed the audio files..
        /// </summary>
        internal static string AudioCompressedText {
            get {
                return ResourceManager.GetString("AudioCompressedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Developed by Studio ACE.
        /// </summary>
        internal static string AuthorSignature {
            get {
                return ResourceManager.GetString("AuthorSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing assets....
        /// </summary>
        internal static string CompressingAssetsText {
            get {
                return ResourceManager.GetString("CompressingAssetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing audio files....
        /// </summary>
        internal static string CompressingAudioFilesText {
            get {
                return ResourceManager.GetString("CompressingAudioFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing database....
        /// </summary>
        internal static string CompressingDatabaseText {
            get {
                return ResourceManager.GetString("CompressingDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing engine files....
        /// </summary>
        internal static string CompressingEngineFilesText {
            get {
                return ResourceManager.GetString("CompressingEngineFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed the database files..
        /// </summary>
        internal static string DatabaseCompressedText {
            get {
                return ResourceManager.GetString("DatabaseCompressedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need to encrypt the archives? (Y/N, default is No).
        /// </summary>
        internal static string EncryptionQuestion {
            get {
                return ResourceManager.GetString("EncryptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed the engine files..
        /// </summary>
        internal static string EngineCompressedText {
            get {
                return ResourceManager.GetString("EngineCompressedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Licesned under the MIT license..
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is not present..
        /// </summary>
        internal static string LocationDoesNotExistText {
            get {
                return ResourceManager.GetString("LocationDoesNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output folder set. The archives will be placed to the project&apos;s folder..
        /// </summary>
        internal static string NoOutputSetText {
            get {
                return ResourceManager.GetString("NoOutputSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password added. The archives will not be encrypted..
        /// </summary>
        internal static string NoPassowrdSetText {
            get {
                return ResourceManager.GetString("NoPassowrdSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project was found..
        /// </summary>
        internal static string NoProjectFoundText {
            get {
                return ResourceManager.GetString("NoProjectFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put the location for the archives (by default it will output the archives to the same location as the game files):.
        /// </summary>
        internal static string OutputLocationQuestion {
            get {
                return ResourceManager.GetString("OutputLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output is now set..
        /// </summary>
        internal static string OutputSetText {
            get {
                return ResourceManager.GetString("OutputSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the password:.
        /// </summary>
        internal static string PasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set. The archives will now be encrypted..
        /// </summary>
        internal static string PasswordSetText {
            get {
                return ResourceManager.GetString("PasswordSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Halva Packer Tool.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Version R1.00 ({0}).
        /// </summary>
        internal static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file package.json isn&apos;t present..
        /// </summary>
        internal static string ProjectFileNotPresentText {
            get {
                return ResourceManager.GetString("ProjectFileNotPresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the project&apos;s files couldn&apos;t be found. Please make sure that the &quot;main&quot; variable in the JSON file is set and points to the correct location..
        /// </summary>
        internal static string ProjectFilesLocationNotFound {
            get {
                return ResourceManager.GetString("ProjectFilesLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is found..
        /// </summary>
        internal static string ProjectFoundText {
            get {
                return ResourceManager.GetString("ProjectFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s the location of the project?.
        /// </summary>
        internal static string ProjectLocationQuestion {
            get {
                return ResourceManager.GetString("ProjectLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===========================================.
        /// </summary>
        internal static string SplitterText {
            get {
                return ResourceManager.GetString("SplitterText", resourceCulture);
            }
        }
    }
}
